library(data.table)
fulldata <- fread("./household_power_consumption.txt")
fulldata$Date <- as.Date(fulldata$Date, format="%d/%m/%Y")
select.data <- subset(fulldata, Date=="2007-02-01" | Date=="2007-02-02")
select.data$Global_active_power <- as.numeric(select.data$Global_active_power)
select.data$Global_reactive_power <- as.numeric(select.data$Global_reactive_power)
select.data$Voltage <- as.numeric(select.data$Voltage)
select.data[,date.time:=paste(as.character(Date),Time)]
formatted.time <- strptime(select.data$date.time, format="%Y-%m-%d %H:%M:%S")
select.data <- cbind(select.data, formatted.time)
par(mfrow=c(2,2))
plot(formatted.time,select.data$Global_active_power, type="l", xlab="", ylab="Global active power (kilowatts)")
plot(formatted.time,select.data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(formatted.time, select.data$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
with(select.data, lines(formatted.time, select.data$Sub_metering_1, col="black"))
with(select.data, lines(formatted.time, select.data$Sub_metering_2, col="red"))
with(select.data, lines(formatted.time, select.data$Sub_metering_3, col="blue"))
legend("topright", lty=1, bty="n", col=c("black","red","blue"), legend=names(select.data)[7:9])
plot(formatted.time, select.data$Global_reactive_power, type="l", xlab="datetime", ylab=names(select.data)[4])
png("plot4.png")
par(mfrow=c(2,2))
plot(formatted.time,select.data$Global_active_power, type="l", xlab="", ylab="Global active power (kilowatts)")
plot(formatted.time,select.data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(formatted.time, select.data$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
with(select.data, lines(formatted.time, select.data$Sub_metering_1, col="black"))
with(select.data, lines(formatted.time, select.data$Sub_metering_2, col="red"))
with(select.data, lines(formatted.time, select.data$Sub_metering_3, col="blue"))
legend("topright", lty=1, bty="n", col=c("black","red","blue"), legend=names(select.data)[7:9])
plot(formatted.time, select.data$Global_reactive_power, type="l", xlab="datetime", ylab=names(select.data)[4])
dev.off()